### ISSUE TITLE
CDNjs and Gitter research

### ISSUE THREAD

**Issue by CharlesLiuyx** [tensorspace-team/tensorspace#109]
- cdnjs

Check this [link](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#a-issue), if we meet the requirements, we could create an issue to request host of out code.

- Gitter

Just login with this [link](https://gitter.im) and choose to host a lobby with you own project

[This link](https://devhints.io/badges) is the Badge cheatsheet, check it when you have the url of our own gitter which is need to be host by the owner of the project

**Comment by syt123450** [comment]
cdnjs latter, close temporarily.
