### ISSUE TITLE
Live Loader for visualizing training process

### ISSUE THREAD

**Issue by syt123450** [tensorspace-team/tensorspace#117]
User can use this loader to load a "live model" (not a pre-trained model), and visualize training process.

Usage:
```
model.load({
    type: "live",
    modelHandler: reference_to_model
});
```

**Comment by syt123450** [comment]
Example to show how to use TensorSpace to visualize the training process of LeNet https://github.com/tensorspace-team/tensorspace/tree/master/examples/trainingLeNet

**Comment by syt123450** [comment]
doc and example gif required @CharlesLiuyx

**Comment by syt123450** [comment]
Playground Online Demo:
https://tensorspace.org/html/playground/trainingLeNet.html

**Comment by CharlesLiuyx** [comment]
Already upload .gif to team driver
