### ISSUE TITLE
Installation [From Scratch]

### ISSUE THREAD

**Issue by joshuagithub** [tensorspace-team/tensorspace#118]
Hi 
I am pretty new here to play with tensorspace.js.  I am able to see the git and stuck to install in my desktop.

My questions 1. do i have to install node.js and npm to run tensorspace.js?

Could you direct me for a quick installation guide? Many thanks.

**Comment by joshuagithub** [comment]
https://tensorspace.org/html/docs/index.html#download
Error page

**Comment by syt123450** [comment]
> https://tensorspace.org/html/docs/index.html#download
> Error page

Thanks for your report, I have fixed the broken link.
The work download link is: https://tensorspace.org/index.html#download

**Comment by syt123450** [comment]
If you want to checkout TensorSpace examples locally, it is not required to use npm or node.js. 

However, if you want to have a look at latest TensorSpace library or try to add new features to TensorSpace, you may need to use npm and run `npm run build` or `npm run build-publish` to build latest TensorSpace, and get the build files in `build` folder.

**Comment by rozester** [comment]
![image](https://user-images.githubusercontent.com/29475143/48923728-c1a55b00-eeb9-11e8-97e8-2678553206dc.png)

When I tried your command "npm run build-publish", I got this error !!!!
