### ISSUE TITLE
visualize the predictions

### ISSUE THREAD

**Issue by NextGuido** [tensorspace-team/tensorspace#121]
@CharlesLiuyx Hi, I got some problems here when I'm trying to visualize the output image with my model. I even couldn't get the prediction result. May you help me with this? And the following is the javascript problems:

Uncaught TypeError: Cannot read property 'dataSync' of undefined
    at Sequential.updateLayerPredictVis (tensorspace.js:2548)
    at Sequential.updateVis (tensorspace.js:2512)
    at Sequential.predict (tensorspace.js:2269)
    at Object.success (unet_sequence.html?_ijt=26969st38nf3fi6d731vk69l6f:150)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

**Comment by syt123450** [comment]
It seems that your pre-trained model do not compatible with TensorSpace, have you preprocessed(about TensorSpace preprocess: https://tensorspace.org/html/docs/preIntro.html) your pre-trained model properly?

Can you provide more code information, such as github repo or codepen, maybe with more information, I can help position problem more precisely.

**Comment by NextGuido** [comment]
@syt123450 thanks a lot! It worked! I did forget to preprocess the model and everything goes well after I did this! You guys really did an amazing job!

**Comment by syt123450** [comment]
@NextGuido You are welcome! Hope you enjoy TensorSpace~

**Comment by NextGuido** [comment]
@syt123450 Hi, I tried adding a self-designed layer with keras using Lambda, but I cannot visualize the model once again! Can you solve this problem?

Uncaught (in promise) Error: Unknown layer: Lambda. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at new t (errors.ts:48)
    at deserializeKerasObject (generic_utils.ts:202)
    at deserialize (serialization.ts:27)
    at i (container.ts:1329)
    at t.fromConfig (container.ts:1355)
    at deserializeKerasObject (generic_utils.ts:235)
    at deserialize (serialization.ts:27)
    at models.ts:270
    at index.ts:79
    at Object.next (index.ts:79)

**Comment by zchholmes** [comment]
@NextGuido From the information you provided, it seems like you have the errors after model conversion. You probably need to register your custom layer before executing the converted tfjs model. 

If that's the issue, you can check the repo from official TensorFlow.js: https://github.com/tensorflow/tfjs-examples/tree/master/custom-layer

If you think that's still not the error source, can you provide more details about the error? 
1. Which stage do you get the error? At preprocessing, building model or loading model?
2. Can you provide more details about your custom layer? Like how to build it?

And it will be helpful if you can provide some sample codes or links that we can have a look.

**Comment by NextGuido** [comment]
@zchholmes Oh, I just wrote the code with keras using a custom layer and use tensorflowjs_converter to convert the model. When I did everthing as before, I met the error. I think you are right for registering my custom layer before executing the converted tfjs model. But I'm not familiar with the tfjs and javascript code. So, is there an easy way solve this?

**Comment by zchholmes** [comment]
@NextGuido At this point, we really can't help too much. Since TensorSpace renders the model in web browser, which is required to consume a web acceptable model format - tensorspace.js model format. For now, there's no way to walk around, especially for the case involves custom layer, which requires extra description and clarification on the layer you customized.
