### ISSUE TITLE
Hello, how can I run this hello world locally?

### ISSUE THREAD

**Issue by yangninghua** [tensorspace-team/tensorspace#133]
I have downloaded and installed node.js

Git your project

cd  E:\ynh\c7\tensorspace-master 

cnpm install tensorspace

cnpm i

npm run build

open helloworld.html

![image](https://user-images.githubusercontent.com/32252319/48964756-6d00fd80-efe9-11e8-9564-72b010c339a2.png)

**Comment by syt123450** [comment]
Have you `start a local web server to view the html file`? 

Directly use "open" command to open html, the url in browser may get a "file://" prefix. The browser will give limit privileges to files in this case.

If you are using some IDE, for example WebStorm, its really easy to start a local server to run TensorSpace examples.
