### ISSUE TITLE
Unsupported Ops in the model before optimization OneShotIterator, IteratorGetNext?

### ISSUE THREAD

**Issue by yts19871111** [tensorspace-team/tensorspace#138]
Unsupported Ops in the model before optimization OneShotIterator, IteratorGetNext ?

**Comment by syt123450** [comment]
Unfortunately, TensorSpace haven't reached pre-processing layer step. However, its really an interesting idea to add pre-processing layers to TensorSpace, if you have any idea which layers can be included, what these layers shall look like, feel free to propose it to us ~
