### ISSUE TITLE
TSP is not defined ReferenceError

### ISSUE THREAD

**Issue by jiaojiaole211** [tensorspace-team/tensorspace#156]
I'am new here. When i run the html from the examples/helloworld/helloworld.html with WebStorm, i got an error as follows:

Uncaught SyntaxError: Unexpected token function
jQuery.Deferred exception: TSP is not defined ReferenceError: TSP is not defined
    at HTMLDocument.<anonymous> (http://localhost:63342/tensorspace-master/examples/helloworld/helloworld.html:42:19)
    at j (http://localhost:63342/tensorspace-master/examples/lib/jquery.min.js:2:29948)
    at k (http://localhost:63342/tensorspace-master/examples/lib/jquery.min.js:2:30262) 
Uncaught ReferenceError: TSP is not defined
  (anonymous function)	
  j	
  k

**Comment by syt123450** [comment]
Hi @jiaojiaole211, have you run `npm run build` to build the latest version of tensorspace.js?

In `examples`, all html files include tensorspace.js from `build` folder
```html
<script src="../../build/tensorspace.js"></script>
```
After clone the TensorSpace repo, you need to run `npm run build` to build the latest tensorspace.js from source code into the `build` folder.

**Comment by jiaojiaole211** [comment]
> 
> 
> Hi @jiaojiaole211, have you run `npm run build` to build the latest version of tensorspace.js?
> 
> In `examples`, all html files include tensorspace.js from `build` folder
> 
> ```
> <script src="../../build/tensorspace.js"></script>
> ```
> 
> After clone the TensorSpace repo, you need to run `npm run build` to build the latest tensorspace.js from source code into the `build` folder.

**Comment by jiaojiaole211** [comment]
> 
> 
> Hi @jiaojiaole211, have you run `npm run build` to build the latest version of tensorspace.js?
> 
> In `examples`, all html files include tensorspace.js from `build` folder
> 
> ```
> <script src="../../build/tensorspace.js"></script>
> ```
> 
> After clone the TensorSpace repo, you need to run `npm run build` to build the latest tensorspace.js from source code into the `build` folder.

@syt123450 hi，i didn't install npm. is there any other way to build tensorspace.js? Thank you very much

**Comment by syt123450** [comment]
Hi @jiaojiaole211, you can replace the
```
<script src="../../build/tensorspace.js"></script>
```
with 
```
<script src="https://cdn.jsdelivr.net/npm/tensorspace@0.2.0/build/tensorspace.min.js"></script>
```
0.2.0 is the latest public version of TensorSpace, I think it can work well with most examples.
