### ISSUE TITLE
Failed to fetch local files when running examples

### ISSUE THREAD

**Issue by BoTime** [tensorspace-team/tensorspace#177]
- Issue
See screenshot below:

![image](https://user-images.githubusercontent.com/25629006/50868376-11ee5480-1364-11e9-834c-d1b1d850a704.png)

- Debugging:
Tried to open this example from WebStorm and it works. But if I open it directly(File -> Open File) from the browser, the error above shows. So I am guessing fetch() api requires a static file server.

**Comment by syt123450** [comment]
TensorSpace must run in web environment. Directly open example files from browser will have errors.
