### ISSUE TITLE
Make easier to find in npm

### ISSUE THREAD

**Issue by Truemedia** [tensorspace-team/tensorspace#184]
Hi, just a small suggestion for improvement.

Currently if you search for "tensor flow" or "tensor space", you won't find this package. If you add a keywords section to the package.json with those and relevant phrases people will find this library easier.

**Comment by syt123450** [comment]
Thanks for your suggestions!

**Comment by Truemedia** [comment]
Can do a pull request if that ok? I have an idea in my head of the keywords and would like to contribute to future development if possible anyway.

**Comment by syt123450** [comment]
@Truemedia PRs welcomed, looking forward to it! If you have any further interesting idea, free free to propose it and it's my pleasure working with you.
