### ISSUE TITLE
Use with model trained in TFJS?

### ISSUE THREAD

**Issue by EddieOne** [tensorspace-team/tensorspace#238]
Hello, How would I use TensorSpace with a model trained in TFJS? I'm trying to find why it is so difficult to train. Is it possible to skip the loading of pretrained model part? 

https://github.com/Y8Games/Y8-Instant-io-Game/blob/ai-gym/src/game.js#L32

https://tensorspace.org/html/docs/preTfjs.html

**Comment by NormanTUD** [comment]
Have you found a solution to this? I'd really like something like

```
tensorspace_model.load(tfjs_model)
```

to skip all the loading and defining stuff, but I cannot find anything like that.

**Comment by EddieOne** [comment]
This was solved using another module. https://github.com/tensorflow/tfjs

**Comment by EddieOne** [comment]
I did not get too far into this project. I'm not clear on the status. I would suggest searching for something newer.
